#!/usr/bin/env bash

declare -r PURPLE="\033[0;35m";
declare -r NC="\033[0m";

echo -e "${PURPLE}Updating compiledb...${NC}";
yes | pip install -U compiledb;
echo "";

echo -e "${PURPLE}Updating nvim...${NC}";
packersync;
echo "";
