#!/usr/bin/env bash

function log()
{
	echo "mk:" "$@";
}

function err()
{
	log "$@" >&2;
}

function require()
{
	command -v "$1" &>/dev/null || {
		err "Couldn't run \`$1'";
		exit 1;
	}
}

################################################################################

require make;

if [[ -f Makefile ]]; then
	log "Using \`Makefile'";
	exec make "${@}";
fi

require git;

[[ "$(git rev-parse --is-inside-work-tree)" == 'true' ]] &>/dev/null || {
	err "Couldn't find \`Makefile' (is not a git repository)";
	exit 1;
}

CWD="$(pwd)";
readonly CWD;

TOPLEVEL="$(git rev-parse --show-toplevel)";
readonly TOPLEVEL;

while [[ "${TOPLEVEL}" != "$(pwd)" ]]; do
	cd ..;
	if [[ -f Makefile ]]; then
		log "Using \`$(realpath --relative-to="${CWD}" "$(pwd)")/Makefile'.";
		exec make "${@}";
	fi
done

err "Couldn't find \`Makefile' in repository";
exit 1;
