#!/usr/bin/env bash

my::exit_err()
{
	echo "mk: couldn't find \`Makefile\`." >&2;
	exit 1;
}

if [[ -f Makefile ]]; then
	make "${@}";
	exit "${?}";
fi

if [[ "$(git rev-parse --is-inside-work-tree)" == 'false' ]]; then
	my::exit_err;
fi

CWD=$(pwd); readonly CWD;
TOPLEVEL=$(git rev-parse --show-toplevel); readonly TOPLEVEL;

while [[ "${TOPLEVEL}" != "$(pwd)" ]]; do
	cd ..;
	if [[ -f Makefile ]]; then
		echo "mk: using \`$(realpath --relative-to="${CWD}" "$(pwd)")/Makefile\`."
		make "${@}";
		exit "${?}";
	fi
done

my::exit_err;
