#!/bin/bash
#
# Filter through lines from stdin using fzf

################################################################################

PROMPT="select tmux theme:";

DOTFILES="${HOME}/.local/share/42dotfiles";

BUILTIN_THEMES="${DOTFILES}/home/private_dot_config/tmux/themes";
LOCAL_THEMES="${HOME}/.config/tmux/themes";

SELECT="$(dirname $0)/select";

################################################################################

THEMES="$( ls -1 "${BUILTIN_THEMES}"; ls -1 "${LOCAL_THEMES}"; )";
echo "${THEMES}" | sort -u | "${SELECT}" "${PROMPT}";
