#!/bin/bash
#
# Filter through lines from stdin using fzf

################################################################################

PROMPT="select tmux theme:"

DOTFILES="${HOME}/.local/share/42dotfiles";

BUILTIN_THEMES="${DOTFILES}/home/private_dot_config/tmux/themes";
LOCAL_THEMES="${HOME}/.config/tmux/themes";

FZF="${DOTFILES}/bin/fzf";
FLAGS=(	--height='~100'				\
		--preview-window='hidden'	\
		--info='hidden'				\
		--disabled					\
		--select-1					\
		--prompt="${PROMPT}" );

################################################################################

THEMES="$( ls -1 "${BUILTIN_THEMES}"; ls -1 "${LOCAL_THEMES}"; )";
echo "${THEMES}" | sort -u | "${FZF}" "${FLAGS[@]}";
